<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find wheelchair_robot)/description/inertial_macros.xacro"/>
    <xacro:include filename="wheelchair_chassis.xacro"/>
    <xacro:include filename="wheelchair_wheel.xacro"/>
    <xacro:include filename="wheelchair_castor_wheel.xacro"/>
    <xacro:include filename="wheelchair_footrest.xacro"/>
    <xacro:include filename="wheelchair_lidar.xacro"/>
    <xacro:include filename="wheelchair_backrest.xacro"/>
    <xacro:include filename="wheelchair_seat.xacro"/>

    <xacro:property name="chassis_x" value="0.8" />
    <xacro:property name="chassis_y" value="0.6" />
    <xacro:property name="chassis_z" value="0.2" />
    <xacro:property name="seat_x" value="0.6" />
    <xacro:property name="seat_y" value="0.6" />
    <xacro:property name="seat_z" value="0.1" />
    <xacro:property name="footrest_x" value="0.15" />
    <xacro:property name="footrest_y" value="0.2" />
    <xacro:property name="footrest_z" value="0.08" />
    <xacro:property name="backrest_x" value="0.2" />
    <xacro:property name="backrest_y" value="0.58" />
    <xacro:property name="backrest_z" value="0.8" />

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1" />
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1" />
    </material>

    <material name="black">
        <color rgba="0 0 0 1" />
    </material>

    <material name="red">
        <color rgba="1 0 0 1" />
    </material>

    <!-- It's standard in ros to callthe first link "base_link" -->
    <!-- For differential driver robot, it's position should be between the rotation wheels because makes the calculation easier (insted of the center of the chassis) -->
    
    <!-- BASE LINK -->
    <link name="base_link"/>

    <!-- CHASSIS -->
    <xacro:wheelchair_chassis name="chassis" parent="base_link" xyz="0 0 0" rpy="0 0 0" chassis_x="${chassis_x}" chassis_y="${chassis_y}" chassis_z="${chassis_z}"/>

    <!-- WHEELS -->
    <xacro:wheelchair_wheel side="right" parent="base_link"  chassis_y="${chassis_y}" xyz="0 0 0" rpy="0 0 0" radius="0.27" width="0.1"/>
    <xacro:wheelchair_wheel side="left"  parent="base_link"  chassis_y="${chassis_y}" xyz="0 0 0" rpy="0 0 0" radius="0.27" width="0.1"/>

    <!-- CASTOR WHEEL -->
    <xacro:wheelchair_castor_wheel side="left" parent="chassis"  chassis_x="${chassis_x}" chassis_y="${chassis_y}" offset_z="-0.1" xyz="0 0 0" rpy="0 0 0" radius="0.17" width="0.1"/>
    <xacro:wheelchair_castor_wheel side="right" parent="chassis"  chassis_x="${chassis_x}" chassis_y="${chassis_y}" offset_z="-0.1" xyz="0 0 0" rpy="0 0 0" radius="0.17" width="0.1"/>
    
    <!-- BACKREST -->
    <xacro:wheelchair_backrest name="backrest" parent="chassis" backrest_x="${backrest_x}" backrest_y="${backrest_y}" backrest_z="${backrest_z}" x="${backrest_x/2}" y="0" z="${backrest_z/2 + chassis_z}" rpy="0 0 0"/>
    <!-- SEAT -->
    <xacro:wheelchair_seat name="seat" parent="chassis" seat_x="${seat_x}" seat_y="${seat_y}" seat_z="${seat_z}" x="${backrest_x + seat_x/2}" y="0" z="0.5" rpy="0 0 0"/>

    <!-- FOOTREST -->
    <xacro:wheelchair_footrest side="left" parent="chassis" fr_x="${footrest_x}" fr_y="${footrest_y}" fr_z="${footrest_z}" x="${chassis_x}" y="${chassis_y}" z="${chassis_z}" rpy="0 0 0"/>
    <xacro:wheelchair_footrest side="right" parent="chassis" fr_x="${footrest_x}" fr_y="${footrest_y}" fr_z="${footrest_z}" x="${chassis_x}" y="${chassis_y}" z="${chassis_z}" rpy="0 0 0"/>

    <!-- LIDAR -->
    <xacro:wheelchair_lidar name="lidar" parent="chassis" support_x="0.05" support_y="${chassis_y - 2*footrest_y}" support_z="0.025" x="${chassis_x + footrest_x}" y="0" z="${footrest_z}" rpy="0 0 0"/>
    <!-- lidar support
    
    lidar -->

</robot>